name: Upload Data - Cron


on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install requirements
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .

    - name: Run - Upload Data
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/owid_lk/upload_data.py --twtr_api_key "${{ secrets.TWTR_API_KEY}}" --twtr_api_secret_key "${{ secrets.TWTR_API_SECRET_KEY}}" --twtr_access_token "${{ secrets.TWTR_ACCESS_TOKEN}}" --twtr_access_token_secret "${{ secrets.TWTR_ACCESS_TOKEN_SECRET}}"

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp -r /tmp/owid_lk.* .
        cp /tmp/README.md .
        git add .
        git commit -m "Updated data $(date)"
        git push origin data
